version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.1
    ports:
      - 5672:5672
  db:
    image: postgres:15.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password123
  